default: &default
  adapter: postgresql
  encoding: unicode
  host: controle-acesso-db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: controle_acesso_development


test:
  <<: *default
  database: controle_acesso_test