default: &default
  adapter: postgresql
  encoding: unicode
  host: controle-turma-db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: controle_turma_development


test:
  <<: *default
  database: controle_turma_test