# FROM node:10-alpine
# ADD ./ /code
# WORKDIR /code
# RUN npm install
# RUN npm install -g @angular/cli@7.0.4
# RUN npm run-script build

# set working directory
# RUN mkdir /src
# WORKDIR /src

# # add `/src/node_modules/.bin` to $PATH
# ENV PATH /src/node_modules/.bin:$PATH

# # install and cache app dependencies
# COPY package.json /src/package.json
# RUN npm install
# RUN npm install -g @angular/cli@1.7.1

# # add app
# COPY . /src

# # start app
# CMD ng serve --host 0.0.0.0


FROM nginx:1.12-alpine
# FROM shakyshane/nginx-cors-plus
# ENV TARGET=google.com
ADD cors_support /etc/nginx/cors_support
COPY ./dist/frontend /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
RUN ls /etc/nginx/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
