version: '0.1'

services:
  # frontend-cadastro:
  #   build: ./frontend
  #   ports:
  #    - "80:80"
  server-cadastro:
    build: ./server
    links:
      - db-cadastro
    ports:
     - "8080:8080"
  db-cadastro:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_DATABASE: 'some_db'
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  # frontend-materia:
  #   build: ./frontend.1
  #   ports:
  #    - "8000:80"
  server-materia:
    build: ./server-1
    links:
      - db-materia
    ports:
     - "8081:8080"
  db-materia:
    container_name: postgres-materia
    image: postgres:10
    environment:
      POSTGRES_DB: 'some_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test_pass'
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data